version: '2'
services:
    portfolio-app:
        image: portfolio
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://portfolio-postgresql:5432/portfolio
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    portfolio-postgresql:
        extends:
            file: postgresql.yml
            service: portfolio-postgresql
